src/components/eventDashboard/submission/SubmissionModule.jsx

fix a :bug:

---

src/components/eventDashboard/submission/SubmissionModule.jsx

Submission module

---

src/components/eventDashboard/EventDashboardPage.jsx
src/components/eventDashboard/submission/SubmissionModule.jsx
src/components/eventDashboard/submission/SubmissionModuleContainer.jsx
src/components/eventDashboard/submission/SubmitObject.jsx
src/components/eventDashboard/submission/SubmitObjectContainer.jsx
src/view/layout.ejs

solve multi entities :bug:

---

docker-compose.yml
npm-shrinkwrap.json
src/components/eventDashboard/submission/SubmitObject.jsx
src/view/layout.ejs
webpack.config.js

teaching cases solved

---

src/components/eventDashboard/payment/ApprovePayment.jsx
src/controllers/fieldRequest/FieldRequest.js
src/controllers/module/PaymentModule.js
src/view/layout.ejs

add cpf to approve payment table

---

src/actions/submission.js
src/components/eventDashboard/submission/SeeToApproveSubmissions.jsx
src/components/eventDashboard/submission/SeeToApproveSubmissionsContainer.jsx
src/components/eventDashboard/submission/SubmissionModule.jsx
src/components/eventDashboard/submission/SubmissionModuleContainer.jsx
src/components/eventDashboard/submission/SubmitObject.jsx
src/components/eventDashboard/submission/SubmitObjectContainer.jsx
src/controllers/event/EventRouter.js
src/controllers/module/PaymentModule.js
src/controllers/module/SubmissionModule.js
src/reducers/submission.js

finish submission evaluation + fix huge submission :bug:

---

src/controllers/module/SubmissionModule.js

fix a huge :bug:

---

webpack.config.js

change bundle

---

src/components/eventDashboard/submission/SubmitObject.jsx
src/components/eventDashboard/submission/SubmitObjectContainer.jsx

set coordinators users free from payment tax

---

src/components/eventDashboard/activities/ActivitiesModule.jsx
src/components/eventDashboard/activities/ConsolidateObject.jsx
src/controllers/event/EventRouter.js
src/controllers/module/ActivitiesModule.js
src/models/activitySession.model.js
webpack.config.js

Activities consolidation

---

src/components/eventDashboard/activities/SeeAllObjectsToEnroll.jsx
src/components/eventDashboard/activities/SeeAllObjectsToEnrollContainer.jsx

- Remove isention to tgs, i will deal with that later
-
-

Enrollment

---

config.TEMPLATE.js
npm-shrinkwrap.json
package.json
src/actions/recoverPassword.js
src/components/Router.jsx
src/components/login/LoginBoard.jsx
src/components/recoverPassword/NewPasswordContainer.jsx
src/components/recoverPassword/NewPasswordPage.jsx
src/components/recoverPassword/RecoverPasswordContainer.jsx
src/components/recoverPassword/RecoverPasswordPage.jsx
src/controllers/user/User.js
src/controllers/user/UserRouter.js
src/models/user.model.js
webpack.config.js

initial release recover password

---

src/controllers/user/UserRouter.js

fix new password url

---

src/components/eventDashboard/activities/SeeAllObjects.jsx
src/components/eventDashboard/activities/SeeAllObjectsToEnroll.jsx
src/components/eventDashboard/submission/ScheduleSubmission.jsx

Remove console logs and now show activities even when not payed

---

src/actions/activities.js
src/actions/submission.js
src/components/eventDashboard/report/UserReport.jsx
src/components/eventDashboard/submission/SeeAllObjects.jsx
src/components/eventDashboard/submission/SeeAllObjectsContainer.jsx
src/components/eventDashboard/submission/SeeObjects.jsx
src/components/eventDashboard/submission/SeeToApproveSubmissions.jsx
src/models/submissionObject.model.js

Mark presence of presentations

---

src/controllers/module/SubmissionModule.js

Now the admin can mark presence

---

src/actions/activities.js
src/components/eventDashboard/activities/SeeAllObjects.jsx
src/components/eventDashboard/activities/SeeAllObjectsContainer.jsx
src/components/eventDashboard/activities/SeeAllObjectsSubmited.jsx
src/components/eventDashboard/activities/SeeAllObjectsToEnroll.jsx
src/controllers/module/ActivitiesModule.js

Add enrollment by admin

---

src/controllers/module/ReportModule.js

fix a huge bug

---

src/controllers/module/ReportModule.js

fix the bug fixing

---

src/components/eventDashboard/activities/SeeAllObjectsEnrolled.jsx
src/components/eventDashboard/activities/SeeAllObjectsToEnroll.jsx

change certificate place

---

src/components/eventDashboard/activities/SeeAllObjectsEnrolled.jsx

fix hakshd

---

src/components/eventDashboard/activities/SeeAllObjectsEnrolled.jsx

fix another huasdh bug

---

src/components/eventDashboard/activities/SeeAllObjectsEnrolled.jsx
src/components/eventDashboard/activities/SeeAllObjectsEnrolledContainer.jsx
src/controllers/module/ActivitiesModule.js

Fixed activity cert

---

src/components/eventDashboard/activities/SeeAllObjectsEnrolled.jsx

Removed a console.log

---

src/actions/activities.js
src/components/eventDashboard/activities/SeeAllObjects.jsx
src/components/eventDashboard/activities/SeeAllObjectsContainer.jsx
src/components/eventDashboard/activities/SeeAllObjectsEnrolled.jsx
src/controllers/module/ActivitiesModule.js

Now you can add cert after the first time

---

public/css/react-datepicker.css
src/actions/activities.js
src/actions/submission.js
src/components/eventDashboard/activities/AdminEntity.jsx
src/components/eventDashboard/activities/ConsolidateObject.jsx
src/components/eventDashboard/activities/ConsolidateObjectContainer.jsx
src/components/eventDashboard/activities/SeeAllObjectsEnrolled.jsx
src/components/eventDashboard/activities/SeeAllObjectsToEnroll.jsx
src/components/eventDashboard/submission/AdminEntity.jsx
src/components/eventDashboard/submission/ScheduleSubmission.jsx
src/components/eventDashboard/submission/ScheduleSubmissionContainer.jsx
src/components/eventDashboard/submission/SeeObjects.jsx
src/controllers/module/ActivitiesModule.js
src/controllers/module/SubmissionModule.js
src/models/activitySession.model.js
src/models/submissionSession.model.js
webpack.config.js

Hour consolidation

---

src/controllers/event/EventRouter.js

Anais issue # .
- Nova Rota de Buscar todos os Submissions e seus arquivos
- Retornar id do grupo tematico
-

 SubmissionsRoute and gts id
